### ISSUE TITLE
Permissions for arbitrary expression dates should be ties to a badge

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#1018]
See e.g. https://edit.laws.africa/works/za-playground/act/by-law/2020/practice-12/amendments

I'm sure this has something to do with the changes we made around amendments / points in time / etc

**Comment by longhotsummer** [comment]
Is it a permission issue? I get a "change date" option in the dropdown.

**Comment by goose-life** [comment]
ah ffs

**Comment by goose-life** [comment]
thanks, I'll have a look!
