### ISSUE TITLE
as an end user I don't want to be misled by the as-at date on the coverpage

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#1027]
e.g. at https://openbylaws.org.za/za/act/gn/2020/318/eng@2020-03-18/ it says 
'[Up to date as at 26 March 2020]' on the coverpage, but as the banner points out 'This is the version of this Government Notice as it was from 18 March 2020 to 24 March 2020.'

The as-at date on the coverpage will continue to be updated because it's worked out based on the latest of the as-at date for the place and the latest published document on the work. However, I think  it's probably inaccurate / meaningless to give an as-at date to a document that is non-current.

To clarify / for background, the use of the as-at date is to let readers know that a document might have a certain expression date (say 12 June 2014) but it was still in force in that exact form as recently as last Friday – it's an artificial end-of-validity date that should continue to be updated as the work continues to not change.

When we have a concrete end-of-validity date, in the form of a more recent point in time or a repeal, the as-at date becomes meaningless – this is no longer the version of the work that we're keeping up to date.

Suggestions:
1. 
- Only keep the as-at date on the coverpages of the most recent published document on a work.
- For all other documents, include a range of valid dates on the coverpage (start = expression date, end = day before new version / repeal comes into force).

In fact, we could use different terminology and have a generic 'valid' date range and work it out on a per-document basis – start date is expression date and end date is the earlier of the next point in time - 1 day, the repeal date - 1 day, and the as-at date for the place (except if the expression date is later than the as-at date, in which case the start and end dates are the same).
We could also include the reason for the end date, e.g.
Valid dates: 12 June 2014 to 3 April 2020 (last check for updates)
Valid dates: 12 June 2014 to 4 March 2019 (day before amendment by GN 12 of 2019)
Valid dates: 3 April 2020 (last check for updates)
etc.
(I don't know about 'Valid dates', I think it can be better.)

2. 
Get rid of the as-at date on the coverpage entirely and only communicate the status of the current document via the / a website UI. (In this case, the banner on OBL is doing everything it needs to.)
This does leave open the question of PDFs that have been downloaded and shared – we shouldn't withhold information from offline end-users if we can help it.

Maybe we keep 'valid dates' on PDF coverpages but don't display them on front ends we have control over, because colourful banners can do more?

@longhotsummer, let me know what you think! I think we can start simple and iterate.

**Comment by goose-life** [comment]
An editor has queried why the as-at date hasn't updated in cases where the work commenced after publication, which I think is a fair question.

https://edit.laws.africa/works/akn/za-ec/act/2020/1/
https://edit.laws.africa/works/akn/ug/act/2006/6/

I think we should consider as-at dates and how they're presented at the same time as thinking about #1221.

**Comment by goose-life** [comment]
Similarly, the as-at date is confusing if a work was repealed afterwards, e.g. https://edit.laws.africa/works/akn/ug/act/ord/1930/16/

**Comment by longhotsummer** [comment]
Updated thoughts are document here: https://docs.google.com/document/d/1-hWp0813J1b8wjdk8coTOFo1NkyATUxTDCBqXR7VYLQ/edit

**Comment by longhotsummer** [comment]
As a reference, this is how we currently determine an individual work's as-at date:

For each work, the effective as-at date (shown on the coverpage) is calculated as the maximum of:
* the place’s as-at date, as set in the place settings page
* the document’s expression date
* the maximum expression date for all published documents in this work

**Comment by goose-life** [comment]
@longhotsummer I think we can close this now that the date information on the coverpage has been rehauled?

**Comment by longhotsummer** [comment]
Yes.
