### ISSUE TITLE
Commencement section ordering

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#1034]
See https://openbylaws.org.za/za/act/gn/2020/318/eng/

Is it correct that it says that "1A to 11G"  commenced on X date? That ordering seems strange.

![Disaster Management Act: Regulations relating to COVID-19 - Open By-laws South Africa 2020-04-15 14-55-02](https://user-images.githubusercontent.com/4178542/79339442-2e931800-7f29-11ea-95a6-cab608208874.png)

**Comment by longhotsummer** [comment]
![Disaster Management Act: Regulations relating to COVID-19 @ 2020-04-02 2020-04-15 14-57-29](https://user-images.githubusercontent.com/4178542/79339628-72861d00-7f29-11ea-86c5-62232f9410e1.png)


It should be ordering the sections more naturally.

**Comment by goose-life** [comment]
While we're in here, let's capitalise the first letter of each commencement string too.

**Comment by goose-life** [comment]
Tbc if we should add full stops sometimes.
