### ISSUE TITLE
some elements are missing their `name` attributes

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#1090]
- [x] act
- [x] FRBRalias
- [x] hcontainer

**Comment by longhotsummer** [comment]
Cobalt now ensures `act` has a name attribute for new documents, but not for old ones.

**Comment by longhotsummer** [comment]
Cobalt also adds `name="title"` for FRBRalias. This will automatically update any time the title attribute is set, which happens whenever a document is saved.
