### ISSUE TITLE
Incorrect linking to partner sites

### ISSUE THREAD

**Issue by mariyabb** [laws-africa/indigo#1192]
As a user I would like to access the correct URL of a piece of legislation access on Commons. 
e.g. https://commons.laws.africa/akn/na/act/1980/21/eng@2019-01-30 
clicking on Read on NamibLII takes me to https://namiblii.org/akn/na/act/1980/21/eng@2019-01-30 which does not exist.
https://namiblii.org/akn/na/act/1980/21 is the correct link.

**Comment by longhotsummer** [comment]
Fixed.
