### ISSUE TITLE
As a reviewer I want to see all signoff tasks across the platform in one view

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#1213]
Proposal:
- Add a permission?
- At https://edit.laws.africa/tasks/ add a 'Signoff' tab, only visible to users with the right permission (include count in tab if possible)
- Add `tasks/signoff/` URL and corresponding view, similar to AvailableTasksView (`AvailableSignoffTasksView`)
- Queryset will filter all tasks by title (this will change once tasks are modelled by type): 'Review and publish changes' and 'Review and sign-off changes'
- Template will look similar to https://edit.laws.africa/tasks/available/ but filter isn't needed (title probably isn't either; we could just link the task number instead?)

**Comment by longhotsummer** [comment]
Cool. Some thoughts:

* perm not critical, anyone can view these tasks anyway
* we already have a task code field (internally), which we can make use of (see screenshot below)
* So a quick option is to add a dropdown to https://edit.laws.africa/tasks/available/ that filters on the code (defaults to "all task types" or similar)
* that way there's no new view, no new templates, just a new filter


![image](https://user-images.githubusercontent.com/4178542/100590895-ad449600-32fd-11eb-85f9-b8920be6b73b.png)

**Comment by longhotsummer** [comment]
Once tasks are modelled by type, we can be smarter?
