### ISSUE TITLE
Change wording of unverified notice for law reform compiled consolidations

### ISSUE THREAD

**Issue by mariyabb** [laws-africa/indigo#1233]
Change the wording of the notice on acts digitized from official consolidations: "[Note: The original publication document is not available and this content could not be verified.]" to wording that reflects the fact that this is an official and authorised (hence verified by the Law Reform Commission) version of legislation

**Comment by longhotsummer** [comment]
I suggest we make this a per-place setting with a default fallback, that is customisable in the place settings UI, rather than doing it in the code.

**Comment by goose-life** [comment]
Great idea!
