### ISSUE TITLE
As a publisher I want to communicate that amendments are being applied to a work

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#1240]
See e.g. the 'Consolidation notice' at http://kenyalaw.org:8181/exist/kenyalex/actview.xql?actid=No.%203%20of%202012 
`(Consolidation of the following amendment ongoing: Act No. 1 of 2020).`
They also do something similar at legislation.gov.uk

This serves to let end users know:
- The document they're currently looking at is out of date
- The editorial team is aware of this and working on it.

It thus increases transparency and helps keep end users well informed.

See also #1221 and #1027

**Comment by goose-life** [comment]
### Proposal
Instead of auto-generating this based on linked but unapplied amendments (which we may want to do eventually):

#### Reader / end user experience
Completely unchanged from the current (see link)

#### Platform UI change
- Under Edit work, add a 'Consolidation note' checkbox.
- If checked, display the following, with the fill-in being required. (In our example, the user would type in 'Act No. 1 of 2020' here.)

- [x] **Consolidation note** `(Consolidation of the following amendment ongoing: `[_______]`).`

#### Model change
- Add `consolidation_note` field to Work model, null and empty both True.

#### Rendering it on the coverpage
- This needs to go on the website, in other words it should be injected into the legacy XML.
- Maybe after the history annotation is generated, check whether the work has a consolidation note on it.
- The XSL-FO should include it, correctly styled, in the PDF.

**Comment by goose-life** [comment]
@longhotsummer thoughts?

**Comment by longhotsummer** [comment]
I think this is a good short-term workaround.

Some thoughts:

* maybe make the entire message customisable, rather than just a portion
* a checkbox implies another field on the model; rather don't have one and just don't use the new new field if it's blank

You'll need to check their existing XML to find out where this needs to go to show up correctly in the  website.

**Comment by longhotsummer** [comment]
This is now important given that we want to be pulling in more principal stubs. I suspect that the API now provides enough information to determine this (ie. the latest available expression is before at least one entry in the `amendments` list), but we'll need to confirm. This will allow consumers to provide a warning notice.

**Comment by goose-life** [comment]
Step 1: verify that the validity dates are accurate

This seems right: https://edit.laws.africa/works/akn/za-playground/act/2022/99/review/
![image](https://user-images.githubusercontent.com/32566441/202171041-c7d5f6d0-0cad-40b9-8015-9dcf0fb91707.png)
![image](https://user-images.githubusercontent.com/32566441/202171226-14146237-371a-47cc-a885-7dbd400009d8.png)

What this tells me is the validity date range takes later amendments into account, regardless of whether there's a document at the later date. 
It does disregard arbitrary points in time / consolidations (whether there is a document or not), which I think is right since those aren't tied to an official change in the content via an amendment.

**Comment by goose-life** [comment]
Step 2 is figuring out what is available via the API for consumers to provide a warning notice.
Specifically: what information is available regarding stubs? and when and how does relationship information get updated?

I think I'll open a separate issue on a different repo for that.

**Comment by goose-life** [comment]
`work_amendments` has been added to the content API; consumers can now work out which amendments haven't yet been applied from that
