### ISSUE TITLE
Whoops, something went wrong. Internal Server Error

### ISSUE THREAD

**Issue by zhyvytskyi** [laws-africa/indigo#1250]
Is it possible to help with Indigo settings?

Problem: Whoops, something went wrong. Internal Server Error
http://15.237.109.225/

**Comment by longhotsummer** [comment]
Hello. The server will show the details of the error in its log files. You can also configure it to send an email with the error details.

You can read more in the Django documentation here: https://docs.djangoproject.com/en/3.1/howto/error-reporting/
