### ISSUE TITLE
as an editor I want to record commencements below the section level

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#1252]
@longhotsummer I don't think we actually have an open issue for this?

# The problem

While we support multiple commencements, we only support them down to the 'section' level, but often subsections, paragraphs, or subparagraphs commence on different dates (or remain uncommenced).

# The desired user experience

1. On the Commencements page of a work, when selecting commenced provisions, instead of being shown a list of sections from which to choose, have a tree view instead, where one can e.g. select all provisions, and then drill down into e.g. Chapter 2, section 4, subsection (2), paragraph (dA), subparagraph (i), subsubparagraph (C), and unselect it.
2. When only some provisions are uncommenced, only show their ancestors, not their siblings; only allow the uncommenced provision itself to be selected (or remain unselected).

# The necessary changes

1. Nest the ToC down to all hierarchical elements, plus `item`. The ToC itself is already hierarchical, which shouldn't change.
2. Change the UI to reflect the ToC tree, and automatically select all children of a selected element by default.
3. Instead of showing the flattened 'commenced provisions' above, show a decorated ToC instead, where each element in the ToC knows whether it's commenced or not.
3. Record every commenced provision (probably no change needed here), i.e. if section 1 and its children are selected also add sec_1__para_a etc to 'commenced provisions'. How 'uncommenced provisions' are worked out should therefore probably not change either.
4. Potentially change the WorkExpression serializer to produce a more descriptive ToC summary, because an API user will get not a lot of value from long lists of eIds, or provide the summary in addition to the serialized ToC?

**Comment by longhotsummer** [comment]
Great. In addition:

## Migration

Once this is implemented, we will need to migrate existing commencement information. For example, if we previously indicated that a commencement event included `['sec_2', 'sec_3']`, we will need to expand that to all the children, eg `['sec_2', 'sec_2__item_a', 'sec_3', 'sec_3__list_1__item_b']` etc.

## API

The API would not be impacted.

**Comment by goose-life** [comment]
## Commencement on insertion

Currently we deal with inserted provisions at the section level by recording the amendment as a partial commencement as well.

Once all provisions can have their own commencement, it'll become more onerous to record a commencement for each inserted provision (it's common for paragraphs, subparagraphs etc. to be inserted or added during an amendment).

We should either make it easier for these to be recorded, perhaps on import from a spreadsheet, or reconsider how we deal with uncommenced provisions.

**Comment by longhotsummer** [comment]
For commencements on insertion: wouldn't the new provisions show up in the commencements view, to be chosen from the list of uncommenced provisions, once the amendments have been applied? ie. wouldn't it actually be fairly easy to capture this detail once amendments have been applied?

That seems easier to me than somehow tagging them in a spreadsheet (and getting IDs wrong, etc.)

**Comment by longhotsummer** [comment]
## UX for checkboxes

1. when unchecking a parent, uncheck the children
2. when checking a parent, check the children
3. if a provision has commenced at another event, but it has uncommenced descendants, then that checkbox must be rendered but disabled (and not have a value)
4.
