### ISSUE TITLE
As a senior editor I want the option to override a place's "no gazette" note per work

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#1263]
e.g. in Uganda the "No Gazette text" is `Note: This version of the Act was revised and consolidated by the Law Reform Commission of Uganda.` (https://edit.laws.africa/places/ug/settings) but there are a handful of Regulations for which the word "Act" is unsuitable.

A user with a Place Admin badge should be able to override the "No Gazette text" for Uganda for that handful of works.

### Proposal

On the work form, at the bottom under a 'Miscellaneous / Additional information' heading, include a "No Gazette" text field.
Always display the place's "No Gazette" text below it, as a guide and for reference. 
This field should only be visible to a Place Admin.
We don't want to inadvertently save an empty string if there's no intention of overriding the note to be blank on this work; but we do also want the option of doing just that. Maybe a checkbox might be best to make it explicit?

On the work model, add a `no gazette text` field, which can be blank and null.
Don't add anything during the migration.

When generating the coverpage, use the work's "No Gazette" text first (if relevant) (this may be an empty string, in which case don't make an empty block), and default to the place's if the work's is null.

**Comment by goose-life** [comment]
This has become relevant again in Tanzania because some post-consolidation works don't have Gazettes – in which case they should display the original 'gazette missing' text. 

I think we might want to approach this question differently, and split out 'no gazette text' from 'information about the consolidation' text? and add a `part_of_consolidation` field to the Work model instead? 

Something to think about.

**Comment by goose-life** [comment]
### Proposal

Model changes:
- `no_publication_document_text` left as is on PlaceSettings model
- 'consolidation_note' text added to PlaceSettings model – exactly the same as the above but without a default
- add a `arbitrary_expression_date_dates` method to WorkMixin that returns a list of arbitrary expression dates on a work

(It will be up to the editors to use generic enough text for the consolidation note, e.g. 'this piece of legislation' rather than 'this Act', for it to be applicable to all works in the consolidation. Note also that this assumes only one consolidation per place, which I think is a good assumption to make for the time being.)

Coverpage template changes:
If an expression / document is at an ArbitraryExpressionDate:
- skip the `publication_document_missing` block entirely
- if the place has a `consolidation_note`, display that in its own block

Place settings form changes:
- Add `consolidation_note` field

Once the new field is added, editors will need to individually separate out 'no Gazette' text from consolidation notes, as they've been combined in this field and we can't fix it in a migration.


@longhotsummer I'd like to prioritise this for next sprint, what do you think?

**Comment by longhotsummer** [comment]
This seems reasonable.
