### ISSUE TITLE
Stop using mimemagic 0.3.5

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#1265]
From https://github.com/laws-africa/indigo/pull/1264/checks?check_run_id=2185011260:
Your bundle is locked to mimemagic (0.3.5), but that version could not be found
in any of the sources listed in your Gemfile. If you haven't changed sources,
that means the author of mimemagic (0.3.5) has removed it. You'll need to update
your bundle to a version other than mimemagic (0.3.5) that hasn't been removed
in order to install.

From https://rubygems.org/gems/mimemagic/versions/0.3.5:
This version has been yanked, and it is not available for download directly or for other gems that may have depended on it.

**Comment by longhotsummer** [comment]
Probably for a security issue.

We should be able to bump to 0.3.6 (the latest in the 0.3 line) without breaking Slaw.

**Comment by goose-life** [comment]
Do you know where we're locked to 0.3.5?

https://github.com/longhotsummer/slaw/blob/d9952b3b3f41847d6ed8c32bb9893182b9b7317a/slaw.gemspec#L28 just means >= 2, right?

**Comment by longhotsummer** [comment]
Or just edit Gemfile.lock and change mimemagic to 0.3.5.
