### ISSUE TITLE
as a reader I want to follow links in legislation

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#1267]
See the links in 
https://commons.laws.africa/akn/za/act/gn/2021/277/eng@2021-03-29.pdf

- http links aren't linked at all
- https links start `https://commons.laws.africa/akn/za/act/gn/2021/277/%255C/%255C/higherhealth.ac.za/` instead of `https://higherhealth.ac.za/`, for example
- from editor: "the first link in 5.7 is working fine and its the only one that doesn't have "https:\\/\\/""

Is this true for web versions as well?

Check on https://openbylaws.org.za/covid19/ once the daily update has run on 10 April.

**Comment by longhotsummer** [comment]
This is because the links URLs themselves have escapes in them, which stems from the fact that we try to escape the forward slashes because to guard against italics 🤦 

![Uploading image.png…]()

**Comment by longhotsummer** [comment]
I've updated the AKN for that work in particular.

**Comment by longhotsummer** [comment]
In ZA, 13 docs have this issue: https://edit.laws.africa/places/za/labs/explorer?xpath=%2F%2Fa%3Aref%5Bcontains%28%40href%2C+%27%5C%2F%27%29%5D&parent=

**Comment by longhotsummer** [comment]
I've fixed all the ZA docs, they still need to be signed off (they're all covid works).

**Comment by longhotsummer** [comment]
This isn't actually a parser issue -- we don't incorrectly escape slashes in attribute values. I think it has been introduced manually by mistake.
