### ISSUE TITLE
As a user I want an informative error message when attempting to create a duplicate commencement

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#1308]
currently users just get a server 500 error

https://sentry.io/organizations/lawsafrica/issues/2514692556/?project=5229057&referrer=slack

**Comment by goose-life** [comment]
The current workaround is to edit the existing commencement by that commencing instrument to have a different date, then create a new one and edit that date, then edit the original back to its date.

Allowing a user to pick a different date before creating the commencement would do away with the error as well as the annoying workaround

**Comment by longhotsummer** [comment]
Can't seem to repro, and the Sentry issue is no more.
