### ISSUE TITLE
Ids in schedule aren't scoped

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#1318]
See https://edit.laws.africa/documents/2318/

![image](https://user-images.githubusercontent.com/4178542/131475002-d031949a-1dee-4e32-b7ff-bf1031349f42.png)

The eIds for attachment elements should have `att_xxx` in them, to ensure they're unique.

Additionally, when rendering, we no longer need to scope the eId with `att_1/...` since that should already be taken care of.

**Comment by goose-life** [comment]
This has been resolved
