### ISSUE TITLE
Where's the "Library" button?

### ISSUE THREAD

**Issue by slbayer** [laws-africa/indigo#1372]
I've downloaded Indigo version 16 and I've got it running - I think. I did not install the example-indigo package. I can create users and works. But on the documentation page "Works and the Library", there's an image of a list of works which looks nothing like my local interface in Indigo 16. How does one get to this view? When I log in, I see this screenshot: 
![Untitled](https://user-images.githubusercontent.com/5578732/145469040-e49b584c-5999-4b71-bf86-34d853cb778f.png)
and I have no idea how to get to the screen shown in the documentation. If I select the "Works" tab, what I see looks nothing like the library listing shown in "Works and the Library". What am I missing? Thanks in advance.

**Comment by longhotsummer** [comment]
Hi there. The documentation is a bit out of date, unfortunately. The Works tab replaces the old library. From there, you can create works and documents.

**Comment by slbayer** [comment]
I appreciate your response. But I can't figure out from the Works tab how to create a document. There doesn't appear to be a button for this either in the Works tab or in the tab for the individual work, even when I edit the work. Alternatively, I can try out an older version of the system. What version of the system does the documentation correspond to?

**Comment by longhotsummer** [comment]
The documentation at https://docs.laws.africa/ is more up to date. Our team is small and we haven’t managed to keep both sets of documentation up to date. 

Start with “creating and editing a work” (https://docs.laws.africa/managing-works/creating-and-editing-works) and then move onto “importing a document” (https://docs.laws.africa/how-tos/importing-a-document). 

You can also work through the full lesson plan. You can largely ignore the information on tasks as they are not that necessary for a single user installation. 

Indigo and it’s approach to akoma ntoso usually requires at least some prior experience or some training. If you can help use understand your use case, we can provide some assistance or guidance. 

Our offices are closing soon for the December holidays, we could set up a call for January if you like?

**Comment by slbayer** [comment]
No need, although I appreciate the offer - what we're doing is a very short-term activity related to getting familiar with AKN and the tools currently available to manipulate it. Your pointers above are VERY helpful - thanks so much.
