### ISSUE TITLE
Feature Request - DB Backend Options

### ISSUE THREAD

**Issue by buff0k** [laws-africa/indigo#1442]
How reliant is the Indigo database model on PGSQL? Couldn't we include ENV variables to use other dj.database options, like MySQL or MariaDB? Adjusting the default config to os.environ.get could implement this?

**Comment by buff0k** [comment]
Another solution which might address this, as well as several other custom configs currently required in settings.py for production use could be to include dotenv for Python? https://stackoverflow.com/questions/58964351/where-environment-variables-for-python-are-saved

**Comment by longhotsummer** [comment]
Indigo is quite closely tied to PostgreSQL and uses certain PostgreSQL features. We don't have the capacity at the moment to implement support for multiple database backends.

If we did look into this, we would need a good motivation to do so. What features would other databases provide that PostgreSQL doesn't?

**Comment by buff0k** [comment]
@longhotsummer Thank you for the response on this, I don't think it is currently warranted, I was curious as to the option, if it was a more agnostic schema I could test deploying differently using the Django utilities.

From my point of view, having to maintain several separate DB back-ends becomes problematic. Currently I have PostgreSQL for Indigo, MariaDB for most of my web-facing applications and Access (Don't even get me started) because Oddyssey POS is backwards. The option to centralize DB functions across any enterprise is always welcome, but I wouldn't consider it a high priority.
