### ISSUE TITLE
As a project owner of a multi-jurisdiction project, I want to be able to add all tasks to one Project

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#1450]
Subject-based projects span jurisdictions, but Projects are place-based.

**Comment by goose-life** [comment]
let's chat with the Content team and get a plan in place this sprint

**Comment by goose-life** [comment]
### Issues

Projects are:
- place-based (so we have many 'Covid-19' or 'Refugees' projects in various jurisdictions)
- work-unaware (so when a sign-off task is automatically created on a work, it doesn't get added to the project)

### Suggestions

- new ProjectsPlus model, one-to-one to TaxonomyTopic, which holds the project description (cf. peachjam Entity (?) model)
- these projects can derive which tasks belong to them via the works with the given topic
- for 'internal only' projects, e.g. 'continuous update' or 'multiple commencements', add a separate root ('Projects') that won't be exposed externally
- on bulk import, the 'Projects' dropdown will be a list of the internal topics instead of a list of projects; subject-area taxonomies will be managed in the spreadsheet same as currently
- global projects view that looks similar to the Projects listing

### Questions

For Dev team:
- where and how does the user manage the ProjectPlus objects?
- can we add descriptions to both internal and external topics? (I'd say yes, they shouldn't be treated any differently)
- do we make 'ghost' ProjectPlus objects for ones that haven't been explicitly created with descriptions, or do we list by taxonomy topic (only if there are tasks), and optionally include the descriptions?
- do we save the tasks to their respective ProjectPlus objects, or is it always worked out dynamically?
    - working out progress bars in the project listing view and in project detail views might become expensive if it's dynamic
    - keeping the ProjectPlus objects up to date will need a bit of work — e.g. every time a new task is created, every time a work's taxonomy topics change, etc

### Previous feedback from Content team

- descriptions are critical
- progress tracker is super useful

**Comment by goose-life** [comment]
Next steps: 
- meet with Content team and describe what we have in mind; get feedback
- do a formal write-up with new models, views, etc

**Comment by actlikewill** [comment]
# Proposal

### Modeling

Add a new Model called ProjectTaxonomy with the following fields:
 - __name__ : (charfield) the name of the project
 - __description__: (textfield)  the description of the project
 - __priority__: (choicefield) the priority of the task
 - __taxonomy__ : (fkfield) foreign key to TaxonomyTopic  

We can also add a new taxonomy tree root called __project__ that will be internal facing and can be filtered out of any content facing views.
Users create new projects by entering a name and linking to a TaxonomyTopic. They should be able to create a project based on any taxonomy, whether its an subject-area taxonomy or internal taxonomy

### Bulk Import
On the bulk import  view the we add a drop down to projecttaxonomy model allowing the created works to be tagged.

### Views

ProjectTaxonomyList View
- Add a new All Projects view that will list entries in the above ProjectTaxonomy model, 
- Add a sort and filter by priority


ProjectTaxonomy Detail View
- This view shows all tasks tagged under the given ProjectTaxonomy
- Add a  filter by place to filter tasks for a given place
