### ISSUE TITLE
As a researcher I want to mark a work as 'commencement date unknown' on the spreadsheet

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#1553]
This will require a new field on the bulk importer.

**Comment by longhotsummer** [comment]
How about `unknown` in the commencement date column?

**Comment by longhotsummer** [comment]
The import form validation is here: https://github.com/laws-africa/indigo/blob/master/indigo/bulk_creator.py#L54

Either that validation must be able to support "unknown", or we need a special date string (eg. 1000-01-01) for unknown.
