### ISSUE TITLE
Docpipe not installing setup.py

### ISSUE THREAD

**Issue by buff0k** [laws-africa/indigo#1559]
It appears that the inclusion of docpipe prevents installation, also having issues manually installing docpipe on Debian.

When "running pip install -e ." it generates an error at the line "'docpipe @ git+https://github.com/laws-africa/docpipe@a149dbaa25de683812d18e74e1c00f30b1522739'," of setup.py

Suspect that the issue relates to docpipe git itself, suggest adding it to PyPi?

**Comment by longhotsummer** [comment]
What is the error? And what version of python and pip are you using?

**Comment by buff0k** [comment]
Hi @longhotsummer 

Python = 3.9.2
PIP = 22.2.2

pip install -e .
Obtaining file:///root/indigo
  Preparing metadata (setup.py) ... done
Collecting docpipe@ git+https://github.com/laws-africa/docpipe@a149dbaa25de683812d18e74e1c00f30b1522739
  Cloning https://github.com/laws-africa/docpipe (to revision a149dbaa25de683812d18e74e1c00f30b1522739) to /tmp/pip-install-c9h397qr/docpipe_c861a2a32f7f4ae0a652ce4603c5ded7
  Running command git clone --filter=blob:none --quiet https://github.com/laws-africa/docpipe /tmp/pip-install-c9h397qr/docpipe_c861a2a32f7f4ae0a652ce4603c5ded7
  Running command git rev-parse -q --verify 'sha^a149dbaa25de683812d18e74e1c00f30b1522739'
  Running command git fetch -q https://github.com/laws-africa/docpipe a149dbaa25de683812d18e74e1c00f30b1522739
  Resolved https://github.com/laws-africa/docpipe to commit a149dbaa25de683812d18e74e1c00f30b1522739
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package docpipe produced metadata for project name unknown. Fix your #egg=docpipe fragments.
Discarding git+https://github.com/laws-africa/docpipe@a149dbaa25de683812d18e74e1c00f30b1522739: Requested unknown from git+https://github.com/laws-africa/docpipe@a149dbaa25de683812d18e74e1c00f30b1522739 (from indigo==17.3.0) has inconsistent name: filename has 'docpipe', but metadata has 'unknown'
Requirement already satisfied: django<4,>=3.2 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (3.2.13)
Requirement already satisfied: boto3>=1.7 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (1.20.24)
Collecting cobalt>=6.0
  Downloading cobalt-6.0.0-py3-none-any.whl (74 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.4/74.4 kB 7.7 MB/s eta 0:00:00
Requirement already satisfied: cssutils>=2.3.0 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (2.3.0)
Requirement already satisfied: django-ckeditor>=5.8 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (6.2.0)
Requirement already satisfied: dj-database-url>=0.3.0 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (0.5.0)
Requirement already satisfied: django-activity-stream>=0.10.0 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (1.4.0)
Requirement already satisfied: django-allauth>=0.48.0 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (0.50.0)
Requirement already satisfied: django-background-tasks>=1.2.5 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (1.2.5)
Requirement already satisfied: django-compressor>=3.1 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (3.1)
Requirement already satisfied: django-cors-headers>=3.11.0 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (3.11.0)
Collecting django-countries-plus<=2.0.0
  Using cached django_countries_plus-2.0.0-py3-none-any.whl (42 kB)
Requirement already satisfied: django-jsonfield>=1.4.1 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (1.4.1)
Requirement already satisfied: django-jsonfield-compat>=0.4.4 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (0.4.4)
Collecting django-filter==2.4.0
  Downloading django_filter-2.4.0-py3-none-any.whl (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.2/73.2 kB 14.3 MB/s eta 0:00:00
Requirement already satisfied: django-fsm>=2.6.0 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (2.8.0)
Requirement already satisfied: django-languages-plus>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (1.1.1)
Requirement already satisfied: django-pipeline>=1.6.11 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (2.0.7)
Requirement already satisfied: django-recaptcha<2.0.0,>=1.4.0 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (1.5.0)
Requirement already satisfied: django-reversion>=3.0.9 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (5.0.0)
Requirement already satisfied: django-sass-processor>=1.1 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (1.1)
Collecting django-sass-processor-dart-sass>=0.0.1
  Downloading django_sass_processor_dart_sass-0.0.1-py3-none-any.whl (3.5 kB)
Requirement already satisfied: django-storages>=1.12.3 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (1.12.3)
Requirement already satisfied: django-templated-email>=2.3.0 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (3.0.0)
Requirement already satisfied: django-wkhtmltopdf>=3.3.0 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (3.4.0)
Requirement already satisfied: djangorestframework-xml>=1.3.0 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (2.0.0)
Requirement already satisfied: djangorestframework<3.12.0,>=3.11.0 in /usr/local/lib/python3.9/dist-packages (from indigo==17.3.0) (3.11.2)
ERROR: Could not find a version that satisfies the requirement docpipe (unavailable) (from indigo) (from versions: 0.0.2)
ERROR: No matching distribution found for docpipe (unavailable)

**Comment by buff0k** [comment]
I have added current 0.0.2 to PyPi, if you want me to grant control to another user for the repo, let me know. This seems to solve the problem with the install and will allow change to setup.py do 'docpipe==0.0.2', instead of the manual GIT pull?

**Comment by longhotsummer** [comment]
> WARNING: Generating metadata for package docpipe produced metadata for project name unknown. Fix your #egg=docpipe fragments.

This seems to be the problem, possibly together with your newer version of pip, I'll look into it.

Right now we don't want the overhead of releasing to pypi -- we using installs from git in many places and they work without a problem.

**Comment by longhotsummer** [comment]
@buff0k additionally, please bear in mind that the master branch is not considered stable and is under active development. For production use, please rely on released versions only.

**Comment by buff0k** [comment]
Seems to deliver the same issue.
Will confirm but I think I did use the cited release tag for the PyPi upload.

**Comment by buff0k** [comment]
> @buff0k additionally, please bear in mind that the master branch is not considered stable and is under active development. For production use, please rely on released versions only.

Which branch would you recommend as released (Note Github not showing any releases)?

main

ancestor-path-tweak

soffice-error

parsing

improvements

act-matcher

**Comment by longhotsummer** [comment]
Releases are here: https://github.com/laws-africa/indigo/releases

So the latest is tag v17.0.0

**Comment by buff0k** [comment]
No idea why it wasn't working but seems to be working now (Tried on multiple LXC containers and bare metal debian-11, may have been a bug resolved with an apt update)

**Comment by longhotsummer** [comment]
Great. It did seem like a pypi or pip bug, rather than on in the package itself.
