### ISSUE TITLE
Consolidation note should only appear for works with a consolidated PIT

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#1598]
For consolidated laws, we have a note that appears at the top, like this:
![image](https://user-images.githubusercontent.com/4178542/197702553-738e614f-c2c2-4087-9311-15d0bc1cc90d.png)

The problem is that the note will appear at the top of all works that are done in full. It should just be on consolidations. Would it be possible that the note is only generated on works that have a "consolidation date" on the timeline? There are quite a lot of Acts in Uganda that were post-consolidation and have been done in full, they all have this note too.

**Comment by goose-life** [comment]
I think we can safely close this; let's reopen if we're given an example.
