### ISSUE TITLE
As a researcher I want to Approve / Unapprove a single work from the work listing view without using bulk actions

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#1931]
- Move the Edit button into a new card footer (only visible to those with permissions)
- Add a single button, Approve / Unapprove, that does the same as the button on the work overview

At the same time, let's move Approve / Unapprove out of bulk actions and into button(s) next to 'Update {{ x }} selected':
- Both 'Approve {{ x }} selected' and 'Unapprove {{ x }} selected', or
- Render only the applicable button(s) based on the selected works, or
- 'Approve / Unapprove {{ x }} selected …' and choose which from a dropdown? (I hate this option)

**Comment by longhotsummer** [comment]
Sounds good.

I did a mockup previously and you'll have to use a fake footer in the `card-body`:

```html
<div class="border-top p-2 bg-light">...</div>
```

or summin'

**Comment by goose-life** [comment]
Okay, we've decided for the bulk approve:
- get one or two lists of works, one to be approved and one to be unapproved
- for each non-empty list, generate a button (Approve … / Unapprove …, or both) with the correct count
- on open, list the works to be approved / unapproved, and a green button
