### ISSUE TITLE
As a researcher I want certain tasks to be automatically created

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#1932]
Currently we only create tasks automatically on bulk import.

We also allow users to block or cancel all tasks on creation.

The main tasks:
- Link gazette (`link-gazette`)
  - Create one of these whenever a work is saved and it doesn't have a publication document.
  - Don't create a duplicate task, UNLESS the existing task is `done`.
- Import content (`import-content`)
  - Create one of these whenever a work is saved if it's either `principal=True` or `stub=False`.
  - Don't create a duplicate task.
- Apply amendment (`apply-amendment`)
  - Create one of these whenever an amendment is saved — adding a date to a task is actually going to be necessary for this.
  - Don't create a duplicate task at the given date.
  - Ideally, if the amendment date was changed, update the date on the existing task too (if it's still open).

(Most of the others are for when there's an error linking things on bulk import, but those should largely fall away as we record information straight on the platform. There might however be new useful task types, especially around pending commencements. We can add support for those later.)

For cancelling / blocking Import and Gazette tasks, we could add a new section at the bottom of the work form (above change place):
- Use htmx to keep an eye on `principal`, `stub`, and `publication_document`.
- If the work already exists, we'll be aware of existing tasks, so we can work out whether new ones will be created.
- List any new tasks that are going to be created here, with a selector of some kind for cancelling OR blocking each of them. 
- (We definitely want the option to e.g. cancel the Gazette task but not the Import task.)
- At some point, add the ability to comment on the task AND/OR edit the task description.

**Comment by longhotsummer** [comment]
If these tasks are only being created once a work is approved, I suggest that Approve pops open a modal that provides checkboxes (ticked by default) to determine which tasks to create. User makes their choice and clicks Approve.

**Comment by goose-life** [comment]
I've been convinced! let's only create tasks on approval 👍

**Comment by goose-life** [comment]
step 1: on Bulk Approve, 
- figure out which tasks will be created, and list them — e.g. 'Import content' and a list of three works, 'Link Gazette' and a list of five
- allow the user to block / cancel each type in bulk
- when they confirm the approval, go ahead and create the tasks, and also cancel / block them as relevant

step 2: do something similar on all other Approves (from work overview, individual work from listing view) — use the bulk logic, but only one work is being approved.

**Comment by goose-life** [comment]
closed by https://github.com/laws-africa/indigo/pull/1951
