### ISSUE TITLE
As an admin I want to prevent some parts of the taxonomy tree from being published in the content API

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#1977]

**Comment by longhotsummer** [comment]
# Proposal

Add a "public" boolean field to the taxonomy topic object, default to `True`. When returning taxonomies via the api, only include those where the *root* taxonomy topic has `public=True`.

Effectively, visibility cascades down the tree. This is less confusing than checking it for every entry or for part-way down the tree.

An alternative is to always check every level, but to have it cascade on save. I think the above is simpler and less error-prone.

**Comment by goose-life** [comment]
closed by https://github.com/laws-africa/indigo/pull/1991
