### ISSUE TITLE
Missing documentation for pagination

### ISSUE THREAD

**Issue by cristiroma** [laws-africa/indigo#2038]
Are there any examples how pagination works for places and works listing within a place? 

I've tried several examples such as https://api.laws.africa/v2/countries.json and https://api.laws.africa/v2/akn/za/.json and other places but I get permission denied on my account.

The API https://developers.laws.africa/api-v2/countries-and-localities does not document: **count**, **next**, **previous** arguments.

**Comment by longhotsummer** [comment]
Hi @cristiroma 

Pagination is described here: https://developers.laws.africa/api-v2/overview#pagination. Basically, you need to check for the “next” URL and use that for your next request. You can see how we handle this in our tutorial project here using a while loop: https://github.com/laws-africa/legislation-reader/blob/main/reader/management/commands/ingest_capetown_bylaws.py#L21

I'll follow up on the other aspects by email.
