### ISSUE TITLE
Get rid of old projects (Workflow model)

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#2039]
* [ ] remove from UI
* [ ] remove models

 **Sanity checks**
- [ ] add/update/remove tasks
- [ ] add/update/remove works 
- [ ] bulk add works
- [ ] bulk update works
- [ ] update tests

**Comment by goose-life** [comment]
@actlikewill as part of this https://github.com/laws-africa/indigo/blob/master/indigo_app/views/places.py#L270 and all of https://github.com/laws-africa/indigo/blob/master/indigo_app/views/places.py#L282-L338 can fall away too
