### ISSUE TITLE
Citator should not look for the act for provisions across sentence boundaries, or too far in general

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#2106]
eg. 
![image](https://github.com/laws-africa/indigo-lawsafrica/assets/4178542/8471f382-7d22-4bf2-818f-b1b4f6d2604e)

**Comment by goose-life** [comment]
is the issue here that section 30 is linking to the Constitution, rather than the Electoral Act?

**Comment by longhotsummer** [comment]
> is the issue here that section 30 is linking to the Constitution, rather than the Electoral Act?

Yes, sorry, that wasn't clear at all.
