### ISSUE TITLE
Not correctly linking to cited provisions

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#2287]

**Comment by goose-life** [comment]
<img width="946" alt="image" src="https://github.com/user-attachments/assets/00df3da2-6fa1-4f70-be8d-01fd8b93cdfb">

https://edit.laws.africa/places/za/tasks/72159

**Comment by longhotsummer** [comment]
Same root cause as #2296 - `item` is not included when looking for numbered elements.

**Comment by longhotsummer** [comment]
Closed in favour of #2296 because identical.
