### ISSUE TITLE
reference to sibling subparagraph missed because they've been marked up as items

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#2288]
![Image](https://github.com/user-attachments/assets/13eb245e-e77f-4e9d-b131-5091193f38c1)

https://edit.laws.africa/places/za/tasks/72160

look at items when resolving subparagraph? (we do for paragraph)

maybe only if we're currently in an item?

**Comment by longhotsummer** [comment]
Similar to #2296
