### ISSUE TITLE
Act references in section headings

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#251]
eg `([Act No. 26 of 2004](/na/act/2004/26))` instead of '([Act No. 26 of 2004](/na/act/2004/26))'

**Comment by longhotsummer** [comment]
Hmm. AKN does technically support inline markup link `ref` in headings. We don't appear to handle it well. In some contexts we need to just use the plain text (eg. TOC generation), in others it may make sense to allow refs.

**Comment by longhotsummer** [comment]
The XML-to-text XSL now supports inline markup in headings.

**Comment by longhotsummer** [comment]
We're very close to this. We support it in the parser for schedule headings, and in rendering in general. We just need to update the parser to support inline elements.

**Comment by longhotsummer** [comment]
This will potentially impact how we generate plain-text headings for TOC elements, which we should be aware of.

**Comment by longhotsummer** [comment]
Done.
