### ISSUE TITLE
as a user, I want all defined terms in a document to be marked up as such

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#259]

**Comment by longhotsummer** [comment]
https://edit.laws.africa/places/za-cpt/tasks/5218/

**Comment by goose-life** [comment]
- User should be able to indicate which sections contain definitions, if it's not automatically detected. 
- Alternatively, user should be able to manually highlight missed terms (not at the start of a line, outside definitions section)
- In the long term, the scope of the term should be considered

Next steps:
- double-check schedules are being checked
- ask editorial team for examples 

If confirmed by editors:
- allow the user to select which sections to look for defined terms in (auto select 'definitions' section if there is one)
- as a temporary workaround, manually bold defined terms that aren't at the start of a line
