### ISSUE TITLE
When reviewing a work, I need to be able to easily access/see the source for the work.

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#280]

**Comment by goose-life** [comment]
- [ ] use form to save work changes
- [ ] handle uploading a file (either new, or to replace an existing one)
- [ ] handle removing the attachment
- [ ] UI to handle attaching a document
- [ ] UI to auto-link to gazette
- [ ] handle new work using new form
- [ ] ensure revisions and `updated_by` when saving/creating a work
- [ ] remove writeable work API

**Comment by longhotsummer** [comment]
Let's see when this comes up and what quick short-term fixes we can put in place to make this easy, and then improve over time.
