### ISSUE TITLE
As an editor I'd like to be able to track tasks that need to be done

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#290]
See #287 for context.

* [x] basic database model
* [x] migrations
* [x] list of tasks in place view
* [x] ability to create a new task from the place view
* [x] ability to edit a task (name and description), for users with appropriate permissions
* [x] ability to close or cancel a task, for users with appropriate permissions
* [x] link in documents and works
* [x] state transitions and appropriate buttons
* [x] appropriate permissions for the above

**Comment by goose-life** [comment]
see https://github.com/laws-africa/indigo/pull/285 for `basic database model`
will tick off once that's been reviewed

**Comment by longhotsummer** [comment]
Cool. See Key Views in https://github.com/laws-africa/indigo/issues/287 for URLs and basic views.

**Comment by longhotsummer** [comment]
Fixed by #285
