### ISSUE TITLE
I want to be able to see the history of task state changes

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#300]

**Comment by goose-life** [comment]
we can keep track of which user _last_ put a task into a state by adding e.g. `last_cancelled_by_user` and `last_cancelled_at` to the model and saving these details whenever the state changes.
but that won't give us a full history.
could we also have something like `previously_cancelled_at {<time>: by <user>}`, which we add to each time we record a new cancellation event on a task?

**Comment by goose-life** [comment]
resolved by #322
