### ISSUE TITLE
As a user I'd like to see a history of activity on a work, document, task, etc.

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#321]
https://github.com/justquick/django-activity-stream

**Comment by longhotsummer** [comment]
# Goals

* When viewing a work or document, help users to understand if it has been recently changed, particularly state changes (eg. publication)
* When viewing a task, help the user to understand how the task has evolved and been changed.
* Store activities for internal metrics and reporting (eg. "how many tasks were closed today?")
* Provide place owners the ability to see recent activity across all works/tasks in the place view.
* Provide insight into a user's activity on the site.

# Backend

* Use django-activity-stream to save state changes
* Integrate with `save` methods or other state changing business logic to trigger state change entries.

# Frontend

## Task view
* Include list of state change activities on tasks, in chronological order. Much like GitHub's issue timeline. We'll add comments at a later stage.

## Contributor view 
* Show recent (?) activity beneath the badges earned box (we'll probably re-work this page later).

# Activities

## Tasks
* X "created" task Y for PLACE
* X "opened/closed/<state changed>" task Y

**Comment by goose-life** [comment]
partially resolved by #322 but we're not yet displaying an activity stream per place, or per work / document

**Comment by longhotsummer** [comment]
Activity stream view added for place, which covers works and documents too.
