### ISSUE TITLE
Indigo uses AKN3 namespace

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#374]
* [x] use new cobalt
* [x] XSLT must change
* [x] Migration to change namespace in all documents (incl. deleted and versions)

**Comment by longhotsummer** [comment]
https://docs.google.com/document/d/1auvOz9juOM2MfVKMRd77Dl6PCtxN6f-nqYvQv6LreQY/edit#

**Comment by longhotsummer** [comment]
I'm working on using the new Cobalt

**Comment by goose-life** [comment]
I'll work on the migration

**Comment by longhotsummer** [comment]
The AKN3 branch now uses the new cobalt.
