### ISSUE TITLE
Icon on task and workflow lists should be top-aligned

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#379]
Also prefer use `.small` class on divs instead of `<small>` so that we get the right line height.

**Comment by longhotsummer** [comment]
Somewhere around https://github.com/laws-africa/indigo/blob/master/indigo_app/templates/indigo_api/_task_list.html#L6 for tasks, workflows will be in the workflow listing template.

**Comment by AliciadW** [comment]
![screenshot 2019-02-20 at 12 11 57](https://user-images.githubusercontent.com/13785692/53084153-ec2ea080-3508-11e9-83c1-9661dc0eb779.png)

@longhotsummer I would like to confirm that this is the icon on the task list that you are referring to.

**Comment by longhotsummer** [comment]
Yes. It's also in the general task list for the country. It uses the same task template.

**Comment by AliciadW** [comment]
https://github.com/laws-africa/indigo/pull/402
