### ISSUE TITLE
Non-image attachments in the attachment view should have a spiffy icon

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#380]

**Comment by longhotsummer** [comment]
Looks like we're using fa-file-pdf-o instead of `far fa-file-pdf` from https://fontawesome.com/icons/file-pdf?style=regular

Check https://github.com/laws-africa/indigo/blob/master/indigo_app/templates/document/_attachments.html#L32 and https://github.com/laws-africa/indigo/blob/master/indigo_app/static/javascript/indigo/views/document_attachments.js#L59

Let's sanity check the other icons while we're at it.

**Comment by AliciadW** [comment]
https://github.com/laws-africa/indigo/pull/401
