### ISSUE TITLE
I'd like to filter tasks by who they've been assigned to

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#386]
### Suggestion
In task list view, give option to exclude tasks submitted by current user

**Comment by longhotsummer** [comment]
Alternatively, a "show my what I can do" view perhaps?

**Comment by longhotsummer** [comment]
I think we should use the same task filtering mechanism in both the task list view and the workflow detail view. We can use the same form on the server, and render the same widgets in the UI.
