### ISSUE TITLE
As a reviewer I want to get a quick idea of key details of a work by hovering over a link to that work

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#388]
For instance, when reviewing that amending information is correct, I don't want to have to click through to the amending work's page. Showing a popover similar to have wikipedia does it would be very helpful.

We could use JS to bind to A tags that link to a work, and use BS4's popover feature to shower a popover box on hover. We can call `.../work/popover` to generate it on the server side.

**Comment by longhotsummer** [comment]
Here's the skeleton of my idea.

1. On page load, wrap a BS4 popover to links to "/works/foo/bar" (or maybe we need to use a `data-popup` to decorate just the ones we want, we'll have to see, otherwise it may decorate "edit this work" buttons.
2. When the popover loads, get the html from `/works/foo/bar/popover`

Something like this (untested):
```js
$('body').on('mouseover', 'a[href^="/works/"]:not(.btn)', function(e) {
  var el = this;
  $.ajax.get(this.href + '/popup').then(function(html) {
    // we probably want to cache html somewhere, for this work on this page
    $(el).popover({content: html}).popover('show');
  });
});
```

The popup could look like a simplified version of this:

<img width="763" alt="nature conservation amendment act 1986 laws africa 2019-02-21 14-41-42" src="https://user-images.githubusercontent.com/4178542/53169742-c4156f00-35e6-11e9-954f-795b964212e9.png">

ie, basic HTML:

* title (bold)
* frbr_uri (muted)
* Promulgation date (publication document isn't crucial)
* assent, commencement date + work
* if repealed, repeal info

**Comment by AliciadW** [comment]
https://github.com/laws-africa/indigo/pull/411
