### ISSUE TITLE
Paginating activity needs to handle many, many pages

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#389]
We need to rethink how we paginate activity. https://edit.laws.africa/places/na/activity

"Page 27" doesn't really help. Perhaps just "older?"

**Comment by longhotsummer** [comment]
Here's the view for the place page: https://github.com/laws-africa/indigo/blob/master/indigo_app/templates/place/activity.html#L12

**Comment by AliciadW** [comment]
https://github.com/laws-africa/indigo/pull/403
