### ISSUE TITLE
As a user I want to be able to assign/unassign tasks in the workflow view

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#408]
In the workflow detail view, I want to be able to assign/unassign a task directly from that view. eg. in the dropdown for each task, show "unassign" or "assign".

If "assign" is chosen, we need a way to list the possible users. It would then submit to the assignment endpoint. We'd need a way to redirect back to the workflow view (eg. a `?next=...`) url.

**Comment by AliciadW** [comment]
https://github.com/laws-africa/indigo/pull/415
