### ISSUE TITLE
Pagination doesn't show ellipsis when on page 6

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#409]
Looks like there's an off-by-one error introduced in #403.

https://edit.laws.africa/places/na/activity?page=6

Before page 2 there should be an ellipsis.

![image](https://user-images.githubusercontent.com/4178542/53282561-f687af00-3741-11e9-8d21-f289ba7838b5.png)

**Comment by AliciadW** [comment]
https://github.com/laws-africa/indigo/pull/412
