### ISSUE TITLE
Cancelled tasks shouldn't be assignable in workflow view

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#443]
Should probably also be un-assigned when it moves into cancelled.

<img width="452" alt="Natural resources-related tasks – Laws Africa 2019-03-25 08-41-07" src="https://user-images.githubusercontent.com/4178542/54899820-d03c6700-4ed9-11e9-9450-6a9701cf95ae.png">

**Comment by longhotsummer** [comment]
At the same time, I think we can remove the "Assigned to" text and move it into the icon's title. I also think the icon doesn't need to be fixed width (`fa-fw`), since that takes up more horizontal space.

**Comment by goose-life** [comment]
@longhotsummer the icon isn't currently `fa-fw` – I've had a look at the styles and there's nothing obvious that can come out that I could see:
`<i class="fas fa-user-tag fa-xs task-icon-assignee"></i>`
Is it possible that the padding is built into the icon itself? Not super obvious from [here](https://fontawesome.com/icons/user-tag?style=solid) but not impossible?

**Comment by longhotsummer** [comment]
Looks like it's because of the task badge. The wrapping `span` can be removed completely I think.

**Comment by goose-life** [comment]
> Looks like it's because of the task badge. The wrapping `span` can be removed completely I think.

Thanks a mil, this seems to have worked!

**Comment by longhotsummer** [comment]
Pls also change the `<div><small class="text-muted">#142</small></div>` to `<div class="small" id="task-142">#142</div>`

That means we can hyperlink to just that task, and it reduces whitespace.

**Comment by longhotsummer** [comment]
Giving the task an ID tag means that after submitting an assign form, we can redirect back to `...#task-123` and have it jump to that task in the list.
