### ISSUE TITLE
As a contributor I want to see photos of other users

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#456]

**Comment by goose-life** [comment]
### The problem
The UserProfile in indigo_social has a profile_photo field (https://github.com/laws-africa/indigo/blob/622b8488a91f93042d4b96bb0f3a1a6fe171dec4/indigo_social/models.py#L18), but we have no mechanism for uploading or displaying a profile photo.

### Solving it
Upload would presumably happen on the UserProfileEditView (https://github.com/laws-africa/indigo/blob/b2d56a0d8fbb0ec95129437de703e5716e268b6c/indigo_social/views.py#L107-L106) (https://edit.laws.africa/accounts/profile/); not sure where it would be stored?

And display at least on the UserProfileView, and the ContributorsView (same file, L29 and L23); although we'll probably also want to eventually display thumbnails all over (similar to GitHub).

Relevant templates I think are all in https://github.com/laws-africa/indigo/tree/master/indigo_social/templates/indigo_social 

### Checklist
- [ ] Upload and store a profile photo
- [ ] Display it on the user profile page
- [ ] Thumbnails everywhere

**Comment by longhotsummer** [comment]
https://django-avatar.readthedocs.io/en/latest/

**Comment by longhotsummer** [comment]
@ro6ley I should say here that we do allow users to log in with Facebook and Google, so can make use of those photos if they don't (or haven't yet) uploaded anything. We use django-allauth for the social login support and stash the data that the social provider gives us in the DB, including image URLs if available.
