### ISSUE TITLE
I'd like to progress a task in a workflow without leaving the page

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#467]
I'd like to make state changes (from `open` to `pending_review` to `closed` etc) to tasks in a workflow without going to individual tasks' detail views – this will save time especially on 'check publication document' tasks, of which we will have many.

**Comment by longhotsummer** [comment]
An option is to have state changes in the dropdown menu for the task.

**Comment by goose-life** [comment]
What we're envisioning is, in this view:
![Screenshot from 2019-04-16 13-07-28](https://user-images.githubusercontent.com/32566441/56204844-ab569200-6048-11e9-9faa-a5d633527d8b.png)

in the dropdown of each task, which currently contains the option to remove form the workflow:
https://github.com/laws-africa/indigo/blob/95c778af9832adc373f9bff1ed51800766a1b701/indigo_app/templates/indigo_api/_task_cards.html#L17-L28

to add the following options:

- [ ] if in the 'Open' column – nothing

- [ ] if in the 'Assigned' column (these are tasks in the `open` state that have an `assigned_to`):
option to 'Submit for review', similar to:
https://github.com/laws-africa/indigo/blob/95c778af9832adc373f9bff1ed51800766a1b701/indigo_app/templates/indigo_api/task_detail.html#L81-L83
- [ ] we want `submit_task_permission` to include the requirement that the task is assigned to the current user – I'll do that part

- [ ] if in the 'Pending review' column:
option to either 'Unsubmit' or 'Close', similar to:
https://github.com/laws-africa/indigo/blob/95c778af9832adc373f9bff1ed51800766a1b701/indigo_app/templates/indigo_api/task_detail.html#L91-L97
- [ ] we want `unsubmit_task_permission` and `close_task_permission` to include the requirement that the current user is both a Senior Drafter and that the task wasn't last_assigned to them – I'll do that part

- [ ] if in the 'Done' or 'Cancelled' columns: nothing.

**Comment by longhotsummer** [comment]
LGTM.

See #490 for task permission changes.

**Comment by AliciadW** [comment]
![Screenshot 2019-05-15 at 15 22 55](https://user-images.githubusercontent.com/13785692/57778931-6ac06600-7725-11e9-836c-91169272f339.png)
![Screenshot 2019-05-15 at 15 22 46](https://user-images.githubusercontent.com/13785692/57778935-6dbb5680-7725-11e9-97f4-f72fe17119f8.png)
![Screenshot 2019-05-15 at 15 22 39](https://user-images.githubusercontent.com/13785692/57778940-6f851a00-7725-11e9-85ec-51f7dc9b1269.png)
![Screenshot 2019-05-15 at 15 23 03](https://user-images.githubusercontent.com/13785692/57778946-7318a100-7725-11e9-8334-4884ee20cbaa.png)

@longhotsummer and/or @goose-life let me know if you want me to see if I can tackle the remaining two list items (including the requirements)

**Comment by goose-life** [comment]
@AliciadW I believe I've done those two outstanding items already; can you make a PR and I'll confirm?

**Comment by AliciadW** [comment]
@goose-life please see PR https://github.com/laws-africa/indigo/pull/554
