### ISSUE TITLE
I'd like to see certain task activities in the workflow detail view

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#469]
Currently workflows' activity streams only include changes to the workflow itself – it might be useful to give certain task state changes too to give an overview of recent activity.
Should it be all state changes?
- [ ] Submitted for review
- [ ] Closed
- [ ] Unsubmitted
- [ ] Cancelled
- [ ] Reopened

thoughts, @longhotsummer?

**Comment by longhotsummer** [comment]
Initially I thought all transitions, but that could be very noisy. An option might be just the changes that impact the completeness of the workflow: closed, cancelled, re-opened?
