### ISSUE TITLE
People shouldn't be able to review their own tasks

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#473]
As a rule, if a task was assigned to someone they should not be able to move that task from `pending_review` to `done`.

We can use the `last_assigned_to` attribute to track this.

We do want an exception to the rule though – a (place) superuser should be trusted to make the call when a task truly does not need to be reviewed.

**Comment by longhotsummer** [comment]
We need to handle this in:

* task detail view
* task list view
* workflow detail view

**Comment by longhotsummer** [comment]
We may want to solve #479 at the same time.
