### ISSUE TITLE
it should be really difficult to lose work in the document editor

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#483]
currently, if I `Edit` a certain section but navigate away from that section (using the sidebar ToC) without first hitting `Update`, there is no warning and any changes made in the editor are lost.

**Comment by goose-life** [comment]
https://github.com/laws-africa/indigo/blob/1b71f4208d3342319cef039c523590dd87ab108c/indigo_app/static/javascript/indigo/views/table_editor.js#L108
Not sure how exactly but this behaviour should also exist in (I think)
https://github.com/laws-africa/indigo/blob/f38cacb9b2916d2636670d9360544870fc483da0/indigo_app/static/javascript/indigo/views/document_editor.js#L318-L322

**Comment by longhotsummer** [comment]
Love the idea.

It'll be a bit more complex: at the point that `discardChanges` is fired, a new item in the table of contents is already selected. We either need to get the tocView to "confirm" with the editor that it can change, or we need to be able to "cancel" the selection event.
