### ISSUE TITLE
as a reviewer I want to see the commencement work on the coverpage of a document

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#489]
This should help at publication stage to check that everything has been recorded.

**Comment by longhotsummer** [comment]
as in "Commences on 1 April 1994 unless otherwise noted" -> "Commences on 1 April 1994 (as per XXX) unless otherwise noted"?

**Comment by goose-life** [comment]
yes, exactly
once multiple commencement dates are supported we can say something like
'whole Act other than section 16 commenced on 1 April 1994 by XXX; section
16 commenced on 1 July 1994 by YYY' etc
but for the time being I just want to verify that the commencement work was
in fact linked without going to the work's timeline (I can verify that all
the other metadata has been captured correctly using the coverpage)

>
