### ISSUE TITLE
As a reviewer I want to be able to easily mark a task as assign-to-me-and-all-done

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#534]
I don't want to have to do the steps separately, when the task is very easy to do. I tend to open the task detail page, do the review, and mark it as done -- without self-assigning the task.

**Comment by longhotsummer** [comment]
We can update the 'closed' and 'cancelled' actions to automatically assign the task to the person doing the action, if no-one else is assigned to the task.

**Comment by goose-life** [comment]
@longhotsummer should we also (for different reasons) make the person who submits the task for review the last_assigned user if the task isn't currently assigned to someone?

**Comment by goose-life** [comment]
- [ ] self-assign if submitting task with no assignee
- [ ] self-assign if approving task with no assignee

**Comment by goose-life** [comment]
@longhotsummer I'm actually not sure why we'd want this for `cancelled`?

**Comment by goose-life** [comment]
https://github.com/laws-africa/indigo/blob/5ba9b777cee8f4212db69a45d0f3a0ba13619635/indigo_api/models.py#L1260-L1263

This seems to ignore who the task is currently assigned to and record the person doing the approving as the person who closed the task, so I'm not sure we need to explicitly assign the task to the reviewer (seeing as that information doesn't get used).

**Comment by longhotsummer** [comment]
> @longhotsummer should we also (for different reasons) make the person who submits the task for review the last_assigned user if the task isn't currently assigned to someone?

Yes.

**Comment by longhotsummer** [comment]
> @longhotsummer I'm actually not sure why we'd want this for `cancelled`?

Actually, that's true.

The motivation for the other states is that if someone has done something on a task, they should be marked as being assigned to it, even historically.

This is good for record-keeping, and will be needed for points and awards.

**Comment by goose-life** [comment]
> The motivation for the other states is that if someone has done something on a task, they should be marked as being assigned to it, even historically.

I'll add something for when it's closed by the user an unassigned
