### ISSUE TITLE
as  a user I want to see the dates on which changes happened on the 'Related works' page

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#631]
so the date of amendments, commencements, repeals (which are no always the same as the commencement date of the work you're viewing)

This will make it easier to double-check that all changes made by a work were captured on the correct date for works with multiple commencement dates.

It will also make it easier to double-check that e.g. all amendment dates have been corrected in the case of a single commencement date that was initially captured incorrectly and has thus been applied in several places.

**Comment by longhotsummer** [comment]
This is done.
