### ISSUE TITLE
As a bulk creator I want more insight into what's going on

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#648]
Preview mode:
- [x] preview of changes that will be made, including errors and existing works
- [x] soft warnings for issues that will cause tasks to be created (eg. missing amending works)
- [x] choose a tab in the spreadsheet (look into possibility / ease)
- [x] icon descriptions: “Created”, “Error - not created”, “Not created, already exists”
- [x] progress bar
- [x] reconsider task creation checkbox/es

Mock up changes

**Comment by longhotsummer** [comment]
Requires #644 to choose tab

**Comment by longhotsummer** [comment]
Done.
