### ISSUE TITLE
country duplicated in work overview and work form

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#665]
![image](https://user-images.githubusercontent.com/32566441/60577334-6efd1d00-9d7f-11e9-94a2-b72b9a746dc5.png)

it's correct for related works, tasks, etc.

![image](https://user-images.githubusercontent.com/32566441/60577395-948a2680-9d7f-11e9-96a3-eca3df2b15b0.png)

**Comment by longhotsummer** [comment]
This is deliberate - in these views, I want the country, locality and FRBR URI to be clear, and not just in the bread crumbs.

Do you think this is a problem?

**Comment by goose-life** [comment]
> Do you think this is a problem?

not really! I just never noticed it before and thought it might've been something I had introduced by accident
