### ISSUE TITLE
as an editor I'd like to be able to mark a PARA as ended

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#729]
when using PARA currently we can't force text to outdent, or for e.g. 1.1 to indent /format correctly (as it does when using section numbering).
see the Schedules of https://edit.laws.africa/works/na/act/2018/17/ for examples

**Comment by longhotsummer** [comment]
<img width="785" alt="National Symbols of the Republic of Namibia Act, 2018 @ 2018-12-28 2019-10-22 14-06-22" src="https://user-images.githubusercontent.com/4178542/67284072-2a83c180-f4d5-11e9-809d-9ba3243ec354.png">

**Comment by longhotsummer** [comment]
See also https://edit.laws.africa/places/za-ec443/tasks/5980/ for subsections.

**Comment by longhotsummer** [comment]
Bluebell fixes this
