### ISSUE TITLE
As an editor amend task without leaving main document

### ISSUE THREAD

**Issue by mariyabb** [laws-africa/indigo#747]
As an Editor, when inside a document I create a task from a comment, I would like to be able to click on the hyperlink to the task and open a new window instead of being prompted to leave the document and open the task interface in the same window.

**Comment by longhotsummer** [comment]
You can hold the Apple key, or shift/control, to open the link in a new tab. Or middle click if you have a three button mouse. 

Greg
--
(iPhone)

**Comment by mariyabb** [comment]
Or you can code a pop-up? 🦄

**Comment by longhotsummer** [comment]
Done.
