### ISSUE TITLE
As an manager, I'd like to see an overview of facts about a place

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#754]
The place detail page currently just lists tasks. The work listing would then move to a new tab (which, in turn, could show 3-4 different ways of listing works).

For instance, the overview should help provide:

* summary of open tasks by state, and by label
* counts of works by subtype and stub (click through to more metrics)
* completeness (click through to more metrics)
* recent activity chart (click through to activity page)
* list of 10 (?) most incomplete works - perhaps ordered by update date
* as at date
* recently updated works
* a list of contributors/top contributors
* link to spreadsheet

Layout-wise, I suggest a collection of cards in columns, perhaps 3-4 per column.

**Comment by longhotsummer** [comment]
I've pushed a basic layout to https://github.com/laws-africa/indigo/tree/place-summary

**Comment by ro6ley** [comment]
Noted

**Comment by longhotsummer** [comment]
# Proposal

Each item is a bootstrap card, and takes up either 1/4, 1/3, 1/2 or a whole column.

## Tasks (1/3 column)
* Heading: Open tasks
* Basic chart (can just use a table with bootstrap progress bars - see how the workflow listing page does it)
* Chart shows count of open tasks by state: open, assigned, pending review
* Click through to place's task listing

## Works (1/3 column)
* Heading: Types of works’
* Same as "Types of works" from https://edit.laws.africa/places/na/metrics

## Works (1/3 column)
* Heading: Stubs and subsidiary legislation
* Two sets of bar charts (can be laid out with bootstrap cols):

```
Stubs  |xxxxxyyyyyyyyy| Non-stubs
```
and
```
Primary |xxxxxxxxyyyyy| Subsidiary
```

Where `|xxxyyyy|` is a progress bar with `x` one colour and `y` another.

## As-at date (1/3 column) - only if not None
* Heading: As-at
* Content: big call-out of date: `YYYY-MM-DD`

## Recent Activity (1/3 column)
* Heading: Recent activity
* Same layout as "changes and updates" chart in http://localhost:8000/places/za/metrics, but over 2 weeks only
* Click-through: metrics page

## Recently updated works (1/2 column)
* Heading: Recently updated
* Table: Work title, frbr uri, and updated date & user

## Recently created works (1/2 column)
* Heading: Recently added
* Table: Work title, frbr uri, and updated date & user

**Comment by ro6ley** [comment]
@longhotsummer I have a question regarding the `Open Tasks` card.

Currently, this is what is in place(all provisional):

![image](https://user-images.githubusercontent.com/8082197/69989953-d1885e00-1555-11ea-88b4-a4268a9fc855.png)
> The completed and canceled tasks appear in the current setup, but that was just for testing purposes.

Question:
Should the `Open Tasks` section be similar to the `Types of Works` section, i.e. have the states on the Y-axis, and the counts on the X-axis?

or 

Should it be just a series of 4 progress bars, with the progress of each state being a percentage of the total number of open tasks?

**Comment by longhotsummer** [comment]
> Should it be just a series of 4 progress bars, with the progress of each state being a percentage of the total number of open tasks?

Let's go with this. The goal is to show information on open tasks -- the total number of closed tasks is not interesting in this case. A bootstrap progress bar for each state would be fine, no need to draw fancy graphs.

eg. something like:

```
(icon) unassigned  |xxxxxx........|  5
(icon) assigned    |xxx...........|  2
```

**Comment by goose-life** [comment]
Suggestion: below 'Recent activity'

Recently submitted tasks (state=pending_review, assigned_to=None)
Columns: Title, Work, Submitted by

Recently added tasks (state=open, assigned_to=None)
Columns: Title, Work, Truncated description?

Recently approved tasks
Columns: Title, Work, Submitted by, Approved by
