### ISSUE TITLE
Attach licensing conditions

### ISSUE THREAD

**Issue by mariyabb** [laws-africa/indigo#756]
As an end user of the PDF, HTML or XML version of legislation, I would like to know what the licensing conditions are, who is the author and where does the source document reside. 
Suggest a link be inserted in each page of the PDF as a footer or header to the Creative Commons license, the author (when it is Laws.Africa) and the link back.
The colophon is not enough.

**Comment by longhotsummer** [comment]
https://docs.google.com/document/d/1xkmCKAagOr552hrNnoqUKV3XzKyR2pZAdpsNTlDF_e8/edit#

**Comment by longhotsummer** [comment]
Improved footer deployed.
