### ISSUE TITLE
As a researcher I'd like advanced work filtering options

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#786]
* repealed (possibly by date)
* commenced/not commenced (possibly by date)
* primary work / subleg
* assent date
* amended or not (by date?)
* publication date

**Comment by longhotsummer** [comment]
I suggest we add an "Advanced filter" section to the work filter page which is hidden by default. When expanded, it can take up as much space as it needs to.

**Comment by longhotsummer** [comment]
A complementary option is to have a set of predefined categories which take you to a pre-filtered page - eg. "repealed works", works by taxonomy, etc.

**Comment by longhotsummer** [comment]
# Proposal

## UX

* In the work filter form at the top of the work list view, we add an "more filters..." option which uses Bootstrap's toggle functionality to then hide the advanced filter options. 
* When rendering, detect if we should automatically show the advanced options if some are applied.
* Move "taxonomies" into advanced to make room.
* The advanced options can afford to take up a bit more space than the normal options.
* Perhaps three columns?

## Backend

* Add additional options to the WorkFilterForm which are optional fields, and default to doing nothing
* So we can safely render these options in the advanced filter section and their default states don't change anything

**Comment by longhotsummer** [comment]
Let's do the basics first. I need to think a bit about how we'd like to filter for subsidiary etc.

**Comment by ro6ley** [comment]
@longhotsummer to clarify, for the date-related fields like `assent date`, will the filtering need to be done by a particular date or in order? Eg by the most recently assented.

Also, Bootstrap does not have an inbuilt date-picker so I am looking into this library: https://bootstrap-datepicker.readthedocs.io/en/latest/index.html

**Comment by longhotsummer** [comment]
> @longhotsummer to clarify, for the date-related fields like `assent date`, will the filtering need to be done by a particular date or in order? Eg by the most recently assented `or` all works assented on 12th December 2018.

Let's make it a filter, so I can choose to see works that have been assented to between dates X and Y.

> Also, Bootstrap does not have an inbuilt date-picker so I am looking into this library: https://bootstrap-datepicker.readthedocs.io/en/latest/index.html

We already have that component installed. If you add `data-provide="datepicker"` to the input element, it'll add it magically.  eg;

```html
<input type="text" class="form-control" data-provide="datepicker" id="..." placeholder="yyyy-mm-dd" pattern="\d{4}-\d\d-\d\d" name="...">
```
