### ISSUE TITLE
make Schedule grammar simpler and clearer

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#792]
* [x] update and release slaw
* [x] updated Gemfile for Indigo
* [x] update act_text.xsl for Indigo
* [x] update ace mode file for Indigo
* [x] update cheatsheet
* [x] update documentation - https://app.gitbook.com/@laws-africa/s/editor-guide/~/drafts/-Ls1P5Voyu-_knQFX1az/primary/editing-a-document/schedules

**Comment by longhotsummer** [comment]
# Proposal

```
SCHEDULE
HEADING The heading [[Section 2(1)]]
SUBHEADING The subheading
```

* Keyword SCHEDULE starts a schedule, like BODY or PREAMBLE
* Heading is strongly modelled with optional HEADING row. If HEADING is not present, "Schedule" is used for the heading.
* Subheading is optional.
* Editorial guidance is to make section reference in the heading as an editorial remark.
* Formatting of section ref can be localised.
* Grammar will support old and new schedule styles to support initial parse from PDF.
* Whitespace between lines is optional.
