### ISSUE TITLE
Schedule entries in ToC missing <ref> contents

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#842]
![image](https://user-images.githubusercontent.com/32566441/68274187-1a411a00-0071-11ea-8caf-42081d946797.png)
![image](https://user-images.githubusercontent.com/32566441/68274201-26c57280-0071-11ea-9e48-8c18b972891e.png)

See https://edit.laws.africa/places/ng/tasks/4484/ on https://edit.laws.africa/documents/3298/

**Comment by longhotsummer** [comment]
Schedule titles are calculated from the `FRBRalias` attribute, which is done by Cobalt.

**Comment by longhotsummer** [comment]
https://github.com/longhotsummer/slaw/pull/41
