### ISSUE TITLE
internal refs finder finding subsections

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#843]
![image](https://user-images.githubusercontent.com/32566441/68322098-7afd4080-00cb-11ea-94f0-7021b0c96ce9.png)

**Comment by goose-life** [comment]
possibly related: not picking up runs when there is a subsection:
![image](https://user-images.githubusercontent.com/32566441/68331964-96257b80-00de-11ea-89f0-74b35eae4a9a.png)

**Comment by longhotsummer** [comment]
I think the subsection markup was the old refs finder, as I can't reproduce this either as a unit test or on this document.
