### ISSUE TITLE
Include place name in generated work coverpage

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#857]
Unless there's a coat of arms, such as in NA.

If we do this by, say, adding an `h3` tag just above the act title, then the generated PDF picks up that content as (a) as the first entry in the TOC and (b) as the running header for the whole document. So this needs to be done without an `h3` tag, but still needs to be styled appropriately by https://github.com/laws-africa/indigo-web

**Comment by goose-life** [comment]
Not sure about the 'unless there's a coat of arms' part. As far as I can tell, Namibia is the exception so far and we manually give it a coat of arms to display, but this isn't in the context, so we can't check for it in the main coverpage html file. 
I'm guessing we could include the coat of arms if it exists in place settings and plug it into the context, and fall back to the place-name if there isn't one. Should we hold off until we have more than one place with a coat of arms before doing that?
