### ISSUE TITLE
As a researcher I'd like to be able to export a CSV/Excel of work details

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#858]
On the work listing page, allow users with a specific permission to download an XSLX file of the metadata of the listed works.

We can use https://xlsxwriter.readthedocs.io/. For the relationships, see the WorkRelatedView logic.

# Proposal

## Frontend

* Just above the work listing table, on the other side of the line from the count of works, add a "Download XSLX" link
* Uses the same URL of the page, but adds `&format=xslx` at the end

## Backend 

* The view creates a helper object which, given an array of Work objects and a file to write to, creates an XSLX file.

#### Sheet 1: works

* FRBR URI
* place: `work.place.place_code`
* title
* subtype
* year
* number
* publication date
* publication name
* publication number
* assent date
* commenced
* commencement date
* repealed date
* parent work: FRBR URI of the parent work
* stub

#### Sheet 2: relationships

* first work (an FRBR URI)
* relationship: amends, repeals, commences, subsidiary of
* second work (an FRBR URI)
* date: optional date (eg. amendment, repeal, etc.)

This sheet only tracks relationships in one direction, the "subject to object" direction. eg. A amends B.

**Comment by goose-life** [comment]
- can we add the 'commenced' boolean on each work to the first sheet?
- we may want to include the extra properties of works (e.g. Cap numbers) on the first sheet; these are set per place iirc?
- I suspect users would prefer a title with the FRBR URIs for both sheets, but that's minor and can be added once the thing is working and we get some user feedback?
- do we need the second sheet? can't we just add an 'amended by' column to the first sheet and give the list of amending works' FRBR URIs? (if it's important to have the relationships separate, remove the ones included on the first sheet (all but 'amended')?)

**Comment by longhotsummer** [comment]
> can we add the 'commenced' boolean on each work to the first sheet?

Added.

> I suspect users would prefer a title with the FRBR URIs for both sheets, but that's minor and can be added once the thing is working and we get some user feedback?

Agreed. We can do that for all references to other works.

> do we need the second sheet?

My primary goal with this is not parity with the legislation spreadsheet, but instead to enable analysis that the platform doesn't currently support. The easiest path to that is to support Excel's pivot tables, which requires that we have one row per work, hence the first sheet. Then, to allow analysis such as "which works does work X amend" we need full relationships, hence the second sheet (but still one relationship per row).

**Comment by goose-life** [comment]
I see, thanks! that makes sense.
- I'd want to then nuke commenced by, repealed by and parent work on the first sheet, but don't feel particularly strongly about it. (especially not parent work)
- Once we support multiple commencement dates and works we'll have to think about how we show them in the export. we could in the second sheet say something like: `{work/provision} commences {provision/s of this work} on {date}`? 
- maybe add {date} for amendments and repeals as well?

**Comment by longhotsummer** [comment]
> I'd want to then nuke commenced by, repealed by and parent work on the first sheet, but don't feel particularly strongly about it. (especially not parent work)

Good idea. Removed, except parent work, since that indicates primary/subsidiary.

> Once we support multiple commencement dates and works we'll have to think about how we show them in the export. we could in the second sheet say something like: {work/provision} commences {provision/s of this work} on {date}?

Yes, something like that. We can add extra columns to characterise the relationship.

> maybe add {date} for amendments and repeals as well?

Yup, included.
