### ISSUE TITLE
as a manager I want to see who is currently working on what

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#881]
Use case: I'm starting a new municipality and want to get an idea of who has which tasks currently assigned to them.

Suggestion: Include 'Tasks currently assigned to {user}' on their profile, as a separate tab / above 'Recent activity'

**Comment by goose-life** [comment]
Same as the 'My tasks' view (https://edit.laws.africa/tasks/) but about someone else.
![image](https://user-images.githubusercontent.com/32566441/70710667-5a3a9300-1ce8-11ea-88b5-a039743f4b09.png)

e.g. https://edit.laws.africa/contributors/robley
![image](https://user-images.githubusercontent.com/32566441/70710728-81916000-1ce8-11ea-844f-31bd13a355f8.png)

Add a new tab next to `Activity` that reads `Tasks` and includes all the info about that user from whatever is in their 'My tasks, view

**Comment by ro6ley** [comment]
Got it @goose-life
