### ISSUE TITLE
Indigo must handle new eId AKN3 attributes

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#955]
## data changes

* [x] Migration to update and move id to eId for historical and deleted documents
* [x] Migration for annotation anchors to use the new IDs
* [x] Migration for internal document refs to use the new IDs
* [x] Migration to create correct term eId attributes

## application logic changes
* [x] XSLT must render id attributes using eId
* [x] annotations etc. must be attached based on eId
* [x] linters must use eId
* [x] internal section refs must use eId
* [x] term tags must use eId and generate appropriate ids
* [x] TLCTerm tags must use eId (but their ids don't need to change)

**Comment by longhotsummer** [comment]
See https://docs.google.com/document/d/1auvOz9juOM2MfVKMRd77Dl6PCtxN6f-nqYvQv6LreQY/edit#

**Comment by longhotsummer** [comment]
## Rendering

* When rendering AKN to HTML, the HTML `id` attribute must come from the new `eId` attribute. The HTML `data-eId` attribute is the value of the `eId` attribute.
* When rendering AKN to HTML for schedules, the scope for the ID prefix will change to the id of the attachment element, rather than the schedule name. for example, `att_1/sec_1`. The renderer in JS and Python must pass in an updated id prefix

**Comment by longhotsummer** [comment]
## Annotations

* When attaching an annotation to element in JS, it must use `eId`. 
* In python, do the same thing for the issue page.

**Comment by longhotsummer** [comment]
# Linters, TOC and issues

* Check that TOC and linter/issue JS uses eId not id

**Comment by longhotsummer** [comment]
# Plugins for finding internal section refs

* use eId not id when looking for referenced provisions

**Comment by longhotsummer** [comment]
For refs: https://github.com/laws-africa/indigo/blob/master/indigo/analysis/refs/base.py#L209

**Comment by longhotsummer** [comment]
Also for refs: https://github.com/laws-africa/indigo/blob/master/indigo/analysis/refs/base.py#L300

**Comment by longhotsummer** [comment]
For terms: https://github.com/laws-africa/indigo/blob/master/indigo/analysis/terms/base.py#L239
